### ISSUE TITLE
org-mode 中文换行会在HTML输出时产生空格

### ISSUE THREAD

**Issue by xuchunyang** [hick/emacs-chinese#1]
从 Github 排版的结果就能看出来。其它的格式，比如：Markdown，都有这个问题，我不知道有没有方法能解决，当然只要不换行就没这个问题。

**Comment by hick** [comment]
我去, 才看到你提了个 issue. 你是不是用 auto-fill-mode 自动分段了?  自动分段插入的就是 \n 这种换行标签,  跟一般的换行没啥差别, 感觉想办法去掉也会非常容易引起其他问题.

**Comment by hick** [comment]
正好这几天留意群里的讨论, 真有几个人写了导出之前去掉的方式.  个人感觉用 truncate-lines 来处理比较好, 更新文档里了 https://github.com/hick/emacs-chinese#中文断行
