### ISSUE TITLE
Windows平台需要修改3行, 否则乱码

### ISSUE THREAD

**Issue by sfengyuan** [hick/emacs-chinese#4]
(when (eq system-type 'windows-nt)
  (set-next-selection-coding-system 'utf-16-le)
  (set-selection-coding-system 'utf-16-le)
  (set-clipboard-coding-system 'utf-16-le))

**Comment by hick** [comment]
多谢, 你这段我也加进去供大家参考

有具体的 windows 版本和  Emacs 版本信息没? 我的设置里没这几行不乱码, 虽然不太理解, 估计跟其他相关设置有点关系.  我的 win7 + eGNU Emacs 24.4.1 (i686-pc-mingw32) of 2014-10-25 on LEG570  只设置了 utf-8 就可以了, 注释部分可以忽略:


![image](https://user-images.githubusercontent.com/38886/52098833-9a7eae80-260b-11e9-882b-2a06131d67ba.png)

**Comment by hick** [comment]
已经更新
